import { readFile, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import { PolicyEngine } from "../../core/policy/engine.js";

function createPolicyViolationError(message, details = {}) {
  const error = new Error(message);
  error.code = "POLICY_VIOLATION";
  error.details = details;
  return error;
}

export const applyPatchTool = {
  name: "apply_patch",
  description: "Apply a patch object generated by create_patch",
  risk: "high",
  inputSchema: {
    type: "object",
    properties: {
      patch: {
        type: "object",
        properties: {
          version: { type: "number" },
          path: { type: "string" },
          newContent: { type: "string" }
        },
        required: ["version", "path", "newContent"],
        additionalProperties: true
      }
    },
    required: ["patch"],
    additionalProperties: false
  },
  async execute(args, context) {
    const patch = args.patch;
    if (!patch || typeof patch.path !== "string" || typeof patch.newContent !== "string") {
      throw new Error("valid patch object is required");
    }
    if (patch.version !== 1) {
      throw new Error(`unsupported patch version: ${patch.version}`);
    }

    const workspaceCwd =
      typeof context.cwd === "string" && context.cwd.length > 0 ? context.cwd : process.cwd();

    const candidatePolicyEngine = context.registry?.policyEngine || context.policyEngine;
    const policyEngine =
      candidatePolicyEngine && typeof candidatePolicyEngine.evaluateWritePath === "function"
        ? candidatePolicyEngine
        : new PolicyEngine();
    const writePathDecision = policyEngine.evaluateWritePath(patch.path, { ...context, cwd: workspaceCwd });
    const absolutePath = writePathDecision.details?.absolutePath || resolve(workspaceCwd, patch.path);

    if (!writePathDecision.allowed) {
      const message = `Write blocked by policy for path: ${absolutePath}`;

      context.onLog?.({
        stage: "policy",
        channel: "security",
        text: `${message} (${writePathDecision.reason})`
      });
      context.eventBus?.emit?.("POLICY_DECISION", {
        source: "apply_patch",
        tool: "apply_patch",
        actionClass: "write",
        approved: false,
        decision: writePathDecision.reason,
        allowed: false,
        reason: writePathDecision.reason
      });

      throw createPolicyViolationError(message, {
        ...writePathDecision.details,
        reason: writePathDecision.reason
      });
    }

    const previousContent = await readFile(absolutePath, "utf8");
    await writeFile(absolutePath, patch.newContent, "utf8");
    return {
      path: relative(workspaceCwd, absolutePath),
      applied: true,
      previousContent,
      newContent: patch.newContent,
      rollbackPatch: {
        version: 1,
        path: patch.path,
        newContent: previousContent
      }
    };
  }
};
