#!/usr/bin/env bash
# Links a working `upstage` command to THIS development checkout, so you can
# run `upstage` from any directory while iterating on the CLI itself.
#
#   ./scripts/dev-link.sh [--force]
#
# Writes a wrapper SCRIPT (not a symlink — the target needs a `bun`
# invocation, not a direct exec, and Windows has no symlink-by-default story;
# see scripts/dev-link.ps1 for the Windows equivalent) to $UPSTAGE_BIN_DIR
# (default ~/.local/bin) that execs `bun <this-repo>/src/cli/index.mjs "$@"`.
# The repo root is resolved once, here, at link time, and baked into the
# wrapper as an absolute path — the resulting `upstage` command works from
# any cwd, and the wrapper never `cd`s into the repo, so the target project's
# cwd is whatever the user was in when they ran `upstage`, not the repo's.
#
# Also writes a marker file (~/.upstage-cli/dev-link.json) that
# `src/cli/lib/install-type.mjs`'s `detectInstallType()` reads — consumed by
# `upstage doctor`/`upstage version --verbose` (once those ship) to report
# "development build" and the repo path.
set -euo pipefail

BIN_DIR="${UPSTAGE_BIN_DIR:-$HOME/.local/bin}"
MARKER_DIR="$HOME/.upstage-cli"
MARKER_FILE="$MARKER_DIR/dev-link.json"
WRAPPER="$BIN_DIR/upstage"
MARKER_TAG="upstage-cli dev-link wrapper"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help)
      echo "Usage: $0 [--force]"
      echo "Links ~/.local/bin/upstage (or \$UPSTAGE_BIN_DIR) to this repo checkout."
      exit 0
      ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
ENTRY="$REPO_ROOT/src/cli/index.mjs"

if [[ ! -f "$ENTRY" ]]; then
  echo "error: expected CLI entry point at $ENTRY — is this script still inside the repo's scripts/ dir?" >&2
  exit 1
fi

if ! command -v bun >/dev/null 2>&1; then
  echo "warning: 'bun' not found on PATH — the dev-linked 'upstage' command will fail until Bun is installed (https://bun.sh)." >&2
fi

if [[ -e "$WRAPPER" && $FORCE -ne 1 ]]; then
  if [[ -L "$WRAPPER" ]]; then
    echo "error: $WRAPPER is a symlink — that looks like a production install (scripts/install.sh's layout)." >&2
    echo "       re-run with --force if you really want to replace it with a dev-link wrapper." >&2
    exit 1
  fi
  if [[ -f "$WRAPPER" ]] && grep -qF "$MARKER_TAG" "$WRAPPER" 2>/dev/null; then
    existing_repo=$(grep -oE "repo: .*" "$WRAPPER" | head -n1 | sed 's/^repo: //')
    if [[ -n "$existing_repo" && "$existing_repo" != "$REPO_ROOT" ]]; then
      echo "error: $WRAPPER is already dev-linked to a different repo:" >&2
      echo "       $existing_repo" >&2
      echo "       re-run with --force to relink it to $REPO_ROOT" >&2
      exit 1
    fi
    # Same repo already linked — relinking is idempotent, no --force needed.
  else
    echo "error: $WRAPPER already exists and is not a recognizable dev-link wrapper." >&2
    echo "       re-run with --force to overwrite it." >&2
    exit 1
  fi
fi

mkdir -p "$BIN_DIR" "$MARKER_DIR"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# $MARKER_TAG -- repo: $REPO_ROOT
# Generated by scripts/dev-link.sh -- do not edit by hand.
# Re-run scripts/dev-link.sh to relink, scripts/dev-unlink.sh to remove.
exec bun "$ENTRY" "\$@"
EOF
chmod +x "$WRAPPER"

linked_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat > "$MARKER_FILE" <<EOF
{
  "repoRoot": "$REPO_ROOT",
  "linkedAt": "$linked_at"
}
EOF

echo "Linked: $WRAPPER -> bun $ENTRY"
echo "Marker: $MARKER_FILE"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "Note: $BIN_DIR is not on your PATH. Add this to your shell profile:"
     echo "  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

echo "Run 'upstage --help' from any directory to verify."
