<#
.SYNOPSIS
    Links a working `upstage` command to THIS development checkout, so you
    can run `upstage` from any directory while iterating on the CLI itself.

.DESCRIPTION
    Writes a wrapper SCRIPT (not a symlink -- Windows has no symlink-by-
    default story, and the target needs a `bun` invocation, not a direct
    exec; see scripts/dev-link.sh for the Unix equivalent) to
    $env:UPSTAGE_BIN_DIR (default: $env:USERPROFILE\.local\bin) that runs
    `bun <this-repo>\src\cli\index.mjs` with all arguments passed through.
    The repo root is resolved once, here, at link time, and baked into the
    wrapper as an absolute path -- the resulting `upstage` command works
    from any cwd, and the wrapper never changes directory into the repo, so
    the target project's cwd is whatever the user was in when they ran
    `upstage`, not the repo's.

    Also writes a marker file ($env:USERPROFILE\.upstage-cli\dev-link.json)
    that src/cli/lib/install-type.mjs's detectInstallType() reads --
    consumed by `upstage doctor`/`upstage version --verbose` (once those
    ship) to report "development build" and the repo path.

.PARAMETER Force
    Overwrite an existing wrapper even if it's dev-linked to a different
    repo, or isn't recognizable as a dev-link wrapper at all.

.EXAMPLE
    powershell -File scripts\dev-link.ps1
    powershell -File scripts\dev-link.ps1 -Force
#>
[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$binDir = if ($env:UPSTAGE_BIN_DIR) { $env:UPSTAGE_BIN_DIR } else { Join-Path $env:USERPROFILE ".local\bin" }
$markerDir = Join-Path $env:USERPROFILE ".upstage-cli"
$markerFile = Join-Path $markerDir "dev-link.json"
$wrapper = Join-Path $binDir "upstage.cmd"
$markerTag = "upstage-cli dev-link wrapper"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "..")).Path.TrimEnd('\')
$entry = Join-Path $repoRoot "src\cli\index.mjs"

if (-not (Test-Path $entry)) {
    Write-Error "expected CLI entry point at $entry -- is this script still inside the repo's scripts\ dir?"
    exit 1
}

if (-not (Get-Command bun -ErrorAction SilentlyContinue)) {
    Write-Warning "'bun' not found on PATH -- the dev-linked 'upstage' command will fail until Bun is installed (https://bun.sh)."
}

if ((Test-Path $wrapper) -and -not $Force) {
    $existingContent = Get-Content $wrapper -Raw -ErrorAction SilentlyContinue
    if ($existingContent -and $existingContent.Contains($markerTag)) {
        if ($existingContent -match "repo:\s*(.+)") {
            $existingRepo = $Matches[1].Trim()
            if ($existingRepo -and $existingRepo -ne $repoRoot) {
                Write-Error "$wrapper is already dev-linked to a different repo:`n  $existingRepo`nRe-run with -Force to relink it to $repoRoot"
                exit 1
            }
        }
        # Same repo already linked -- relinking is idempotent, no -Force needed.
    } else {
        Write-Error "$wrapper already exists and is not a recognizable dev-link wrapper.`nRe-run with -Force to overwrite it."
        exit 1
    }
}

New-Item -ItemType Directory -Force -Path $binDir | Out-Null
New-Item -ItemType Directory -Force -Path $markerDir | Out-Null

$wrapperContent = @"
@echo off
rem $markerTag -- repo: $repoRoot
rem Generated by scripts\dev-link.ps1 -- do not edit by hand.
rem Re-run scripts\dev-link.ps1 to relink, scripts\dev-unlink.ps1 to remove.
bun "$entry" %*
exit /b %ERRORLEVEL%
"@

Set-Content -Path $wrapper -Value $wrapperContent -Encoding ascii -NoNewline

$linkedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$markerObject = [ordered]@{ repoRoot = $repoRoot; linkedAt = $linkedAt }
$markerJson = $markerObject | ConvertTo-Json
Set-Content -Path $markerFile -Value $markerJson -Encoding utf8

Write-Host "Linked: $wrapper -> bun $entry"
Write-Host "Marker: $markerFile"

$pathDirs = $env:PATH -split ';' | Where-Object { $_ }
if ($pathDirs -notcontains $binDir) {
    Write-Host "Note: $binDir is not on your PATH. Add it, e.g.:"
    Write-Host "  [Environment]::SetEnvironmentVariable('PATH', `"`$env:PATH;$binDir`", 'User')"
    Write-Host "  (then restart your terminal)"
}

Write-Host "Run 'upstage --help' from any directory to verify."
