// `upstage completion bash|zsh|fish|powershell` — Task 7.18 of the 3.2.0
// release plan (§6 command tree, §7.18 design detail).
//
// Generates a shell completion script AT RUNTIME, introspecting the router's
// own `COMMANDS` table (src/cli/router.mjs) rather than duplicating a parallel
// hardcoded command list — per the task's explicit failure-mode warning: a
// hand-maintained list would silently drift the first time a command is
// added to the router. `buildCommandTree()` below is the ONLY place that
// walks `COMMANDS`, and every shell generator consumes its output, never the
// raw router table directly.
//
// `COMMANDS` node shapes actually used across this branch's ~24 prior tasks
// (see router.mjs's own header comment) are exactly two, and `buildCommandTree`
// distinguishes them structurally rather than by which helper built them:
//   - `{ handler, usage? }` — a leaf (built via router.mjs's `leaf()` helper,
//     OR a hand-wired object with a real command handler + usage string).
//   - `{ subcommands: { ... } }` — a namespace (built via router.mjs's
//     `namespace()` helper, OR a hand-wired object like `config`/`mcp`/
//     `sessions` etc. whose subcommand values are themselves leaves).
// Both shapes collapse to "does this node have a `.subcommands` object?" —
// so one recursive walk handles the mix uniformly, with no shape-specific
// special-casing required (and no arbitrary depth limit, though in practice
// this branch's table never nests deeper than namespace -> leaf).
//
// Like `gh completion -s bash`/`docker completion bash`, this project prints
// the generated script to stdout for the user to redirect/source/eval
// themselves — it MUST NOT write to a user's ~/.bashrc, ~/.zshrc, PowerShell
// $PROFILE, etc. automatically.
//
// The CLI wiring in router.mjs does NOT import anything from this module
// that would create a circular `router.mjs <-> completion.mjs` import back
// onto `COMMANDS` — `createCompletionHandler(shell, getCommandTable)` below
// takes a zero-arg getter instead, so router.mjs can pass `() => COMMANDS`
// (a closure over its own local binding) without either module importing
// the other.

export const SUPPORTED_SHELLS = ["bash", "zsh", "fish", "powershell"];

/**
 * Walks a router `COMMANDS`-shaped table into a plain nested-name tree:
 * `{ [commandName]: null | { [subcommandName]: null | { ... } } }`.
 * `null` marks a leaf (no subcommands). Every shell generator below builds
 * off this tree, never off the raw router nodes (which also carry
 * `handler`/`usage` fields irrelevant to completion).
 */
export function buildCommandTree(commandTable) {
  const tree = {};
  for (const [name, node] of Object.entries(commandTable || {})) {
    if (node && node.subcommands && typeof node.subcommands === "object") {
      tree[name] = buildCommandTree(node.subcommands);
    } else {
      tree[name] = null;
    }
  }
  return tree;
}

function sortedNames(tree) {
  return Object.keys(tree).sort();
}

function hasSubcommands(tree, name) {
  return tree[name] && sortedNames(tree[name]).length > 0;
}

const GENERATED_BANNER =
  "Generated by `upstage completion` — do not edit by hand. Regenerate with the same command whenever upstage's command list changes.";

// ── bash ─────────────────────────────────────────────────────────────────

// A literal bash variable reference, kept as a named constant (rather than
// inlined via a confusing `${"${cur}"}` nested-string trick) so it reads
// clearly as bash text being interpolated into a JS template literal
// alongside actual JS values like `top.join(" ")`.
const BASH_CUR_REF = "${cur}";

function generateBash(tree) {
  const top = sortedNames(tree);
  const lines = [
    "#!/usr/bin/env bash",
    "# bash completion for upstage",
    `# ${GENERATED_BANNER}`,
    "#",
    "# Usage:",
    "#   source <(upstage completion bash)",
    "#   # or persist it: upstage completion bash > /etc/bash_completion.d/upstage",
    "",
    "_upstage_completion() {",
    "  local cur top_command",
    '  COMPREPLY=()',
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    "",
    "  if [[ ${COMP_CWORD} -eq 1 ]]; then",
    `    COMPREPLY=( $(compgen -W "${top.join(" ")}" -- "${BASH_CUR_REF}") )`,
    "    return 0",
    "  fi",
    "",
    '  top_command="${COMP_WORDS[1]}"',
    "  case \"${top_command}\" in"
  ];

  for (const name of top) {
    if (!hasSubcommands(tree, name)) continue;
    const subs = sortedNames(tree[name]).join(" ");
    lines.push(`    ${name})`);
    lines.push("      if [[ ${COMP_CWORD} -eq 2 ]]; then");
    lines.push(`        COMPREPLY=( $(compgen -W "${subs}" -- "${BASH_CUR_REF}") )`);
    lines.push("        return 0");
    lines.push("      fi");
    lines.push("      ;;");
  }

  lines.push("  esac");
  lines.push("");
  lines.push('  COMPREPLY=( $(compgen -f -- "${cur}") )');
  lines.push("}");
  lines.push("");
  lines.push("complete -F _upstage_completion upstage");
  lines.push("");
  return lines.join("\n");
}

// ── zsh ──────────────────────────────────────────────────────────────────

function zshArrayLiteral(names) {
  return names.map((n) => `'${n}'`).join(" ");
}

function generateZsh(tree) {
  const top = sortedNames(tree);
  const lines = [
    "#compdef upstage",
    "# zsh completion for upstage",
    `# ${GENERATED_BANNER}`,
    "#",
    "# Usage:",
    "#   upstage completion zsh > \"${fpath[1]}/_upstage\"",
    "#   # then start a new shell, or run: autoload -U compinit && compinit",
    "",
    "_upstage() {",
    "  local -a commands",
    `  commands=(${zshArrayLiteral(top)})`,
    "",
    "  if (( CURRENT == 2 )); then",
    "    _describe 'command' commands",
    "    return",
    "  fi",
    "",
    '  case "${words[2]}" in'
  ];

  for (const name of top) {
    if (!hasSubcommands(tree, name)) continue;
    const subs = sortedNames(tree[name]);
    lines.push(`    ${name})`);
    lines.push("      local -a subcommands");
    lines.push(`      subcommands=(${zshArrayLiteral(subs)})`);
    lines.push("      _describe 'subcommand' subcommands");
    lines.push("      ;;");
  }

  lines.push("    *)");
  lines.push("      _files");
  lines.push("      ;;");
  lines.push("  esac");
  lines.push("}");
  lines.push("");
  lines.push('_upstage "$@"');
  lines.push("");
  return lines.join("\n");
}

// ── fish ─────────────────────────────────────────────────────────────────

function generateFish(tree) {
  const top = sortedNames(tree);
  const lines = [
    "# fish completion for upstage",
    `# ${GENERATED_BANNER}`,
    "#",
    "# Usage:",
    "#   upstage completion fish | source",
    "#   # or persist it: upstage completion fish > ~/.config/fish/completions/upstage.fish",
    "",
    "complete -c upstage -f",
    "",
    `complete -c upstage -n "__fish_use_subcommand" -a "${top.join(" ")}"`
  ];

  for (const name of top) {
    if (!hasSubcommands(tree, name)) continue;
    const subs = sortedNames(tree[name]).join(" ");
    lines.push(
      `complete -c upstage -n "__fish_seen_subcommand_from ${name}" -a "${subs}"`
    );
  }

  lines.push("");
  return lines.join("\n");
}

// ── powershell ───────────────────────────────────────────────────────────
//
// Per §7.18's design detail, this MUST use `Register-ArgumentCompleter
// -Native` (the mechanism PowerShell provides for completing external/native
// commands like `upstage.exe`, as opposed to `-CommandName` completers for
// PowerShell functions/cmdlets themselves).

function powershellHashtableLiteral(tree, top) {
  const lines = ["@{"];
  for (const name of top) {
    const subs = hasSubcommands(tree, name) ? sortedNames(tree[name]) : [];
    const subsLiteral = subs.map((s) => `'${s}'`).join(", ");
    lines.push(`  '${name}' = @(${subsLiteral})`);
  }
  lines.push("}");
  return lines.join("\n");
}

function generatePowerShell(tree) {
  const top = sortedNames(tree);
  const lines = [
    "# PowerShell completion for upstage",
    `# ${GENERATED_BANNER}`,
    "#",
    "# Usage:",
    "#   upstage completion powershell | Out-String | Invoke-Expression",
    "#   # or persist it in $PROFILE:",
    "#   #   upstage completion powershell >> $PROFILE",
    "",
    "$upstageCommandTree = " + powershellHashtableLiteral(tree, top),
    "",
    "Register-ArgumentCompleter -Native -CommandName upstage -ScriptBlock {",
    "  param($wordToComplete, $commandAst, $cursorPosition)",
    "",
    "  $tokens = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })",
    "",
    "  if ($tokens.Count -le 2) {",
    "    $candidates = $upstageCommandTree.Keys",
    "  } else {",
    "    $topCommand = $tokens[1]",
    "    if ($upstageCommandTree.ContainsKey($topCommand)) {",
    "      $candidates = $upstageCommandTree[$topCommand]",
    "    } else {",
    "      $candidates = @()",
    "    }",
    "  }",
    "",
    "  $candidates |",
    "    Where-Object { $_ -like \"$wordToComplete*\" } |",
    "    Sort-Object |",
    "    ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }",
    "}",
    ""
  ];
  return lines.join("\n");
}

// ── dispatch ─────────────────────────────────────────────────────────────

const GENERATORS = {
  bash: generateBash,
  zsh: generateZsh,
  fish: generateFish,
  powershell: generatePowerShell
};

/**
 * Generates one shell's completion script text from a router `COMMANDS`-
 * shaped table. This is the module's core contract — pure, no I/O — so it
 * can be unit-tested directly against a real or fixture command table.
 */
export function generateCompletion(shell, commandTable) {
  const generator = GENERATORS[shell];
  if (!generator) {
    throw new Error(
      `Unsupported shell "${shell}". Expected one of: ${SUPPORTED_SHELLS.join(", ")}`
    );
  }
  const tree = buildCommandTree(commandTable);
  return generator(tree);
}

function usageFor(shell) {
  return [
    `Usage: upstage completion ${shell}`,
    "",
    `  Prints a ${shell} completion script to stdout, generated from upstage's`,
    "  live command table. Redirect or eval it yourself — this command never",
    "  writes to your shell profile."
  ].join("\n");
}

/**
 * Builds a router-compatible handler bound to one shell. `getCommandTable`
 * is a zero-arg getter (router.mjs passes `() => COMMANDS`) rather than the
 * table itself, so this module never needs to import router.mjs (avoiding a
 * router.mjs <-> completion.mjs circular import) and always sees the live
 * table at call time.
 */
export function createCompletionHandler(shell, getCommandTable) {
  return async function runCompletionShellCommand(argv) {
    if (argv.includes("-h") || argv.includes("--help")) {
      process.stdout.write(`${usageFor(shell)}\n`);
      return 0;
    }
    const commandTable = getCommandTable();
    const script = generateCompletion(shell, commandTable);
    process.stdout.write(script.endsWith("\n") ? script : `${script}\n`);
    return 0;
  };
}
